namespace FibonacciApi.Models
{
    /// <summary>
    /// Describes a FibonacciRequest made at a specific time.
    /// </summary>
    public class FibonacciRequest
    {
        /// <summary>
        /// Gets or sets the Id of the request (Auto-generated by EF).
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the Time this request was made (DateTimeOffset for UTC standard).
        /// </summary>
        public DateTimeOffset Time { get; set; }

        /// <summary>
        /// Gets or sets the requested number.
        /// </summary>
        public int Number { get; set; }

        /// <summary>
        /// Gets or sets the resulting Fibonacci number.
        /// </summary>
        public string? Result { get; set; }
    }
}
